// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\ModeS_ADI_Codegen\Detector_ip_src_CalcMagnitude.v
// Created: 2017-07-24 12:12:58
// 
// Generated by MATLAB 9.2 and HDL Coder 3.10
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Detector_ip_src_CalcMagnitude
// Source Path: ModeS_ADI_Codegen/Detector/CalcMagnitude
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Detector_ip_src_CalcMagnitude
          (clk,
           reset,
           enb,
           In1,
           In2,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In1;  // sfix16_En15
  input   signed [15:0] In2;  // sfix16_En15
  output  signed [15:0] Out1;  // sfix16_En15

  wire signed [31:0] Product_mul_temp;  // sfix32_En30
  wire signed [15:0] Product_out1;  // sfix16_En15
  reg signed [15:0] Delay15_out1;  // sfix16_En15
  wire signed [31:0] Product1_mul_temp;  // sfix32_En30
  wire signed [15:0] Product1_out1;  // sfix16_En15
  reg signed [15:0] Delay16_out1;  // sfix16_En15
  wire signed [15:0] Add_out1;  // sfix16_En15


  // <S7>/Product
  assign Product_mul_temp = In1 * In1;
  assign Product_out1 = Product_mul_temp[30:15];



  // <S7>/Delay15
  always @(posedge clk or posedge reset)
    begin : Delay15_process
      if (reset == 1'b1) begin
        Delay15_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay15_out1 <= Product_out1;
        end
      end
    end



  // <S7>/Product1
  assign Product1_mul_temp = In2 * In2;
  assign Product1_out1 = Product1_mul_temp[30:15];



  // <S7>/Delay16
  always @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        Delay16_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay16_out1 <= Product1_out1;
        end
      end
    end



  // <S7>/Add
  assign Add_out1 = Delay15_out1 + Delay16_out1;



  assign Out1 = Add_out1;

endmodule  // Detector_ip_src_CalcMagnitude

