// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\ModeS_ADI_Codegen\Detector_ip_src_Check_CRC.v
// Created: 2017-07-24 12:12:58
// 
// Generated by MATLAB 9.2 and HDL Coder 3.10
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Detector_ip_src_Check_CRC
// Source Path: ModeS_ADI_Codegen/Detector/CalcCRC/Check_CRC
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Detector_ip_src_Check_CRC
          (clk,
           reset,
           enb,
           Bits,
           CRC,
           rst,
           CRC_Chk);


  input   clk;
  input   reset;
  input   enb;
  input   Bits;
  input   CRC;
  input   rst;
  output  CRC_Chk;

  wire Logical_Operator_out1;
  wire Logical_Operator1_out1;
  reg  Delay_switch_delay;  // ufix1
  wire Delay_out1;
  wire Logical_Operator2_out1;

  // Compare received CRC with computed CRC
  // If there are any differences, output zero/false, one/true otherwise.
  // 
  // Comparison
  // 
  // Remember any difference


  // <S19>/Logical Operator
  assign Logical_Operator_out1 = Bits ^ CRC;



  // <S19>/Delay
  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_switch_delay <= 1'b0;
      end
      else begin
        if (enb) begin
          if (rst == 1'b1) begin
            Delay_switch_delay <= 1'b0;
          end
          else begin
            Delay_switch_delay <= Logical_Operator1_out1;
          end
        end
      end
    end

  assign Delay_out1 = (rst == 1'b1 ? 1'b0 :
              Delay_switch_delay);



  // <S19>/Logical Operator1
  assign Logical_Operator1_out1 = Logical_Operator_out1 | Delay_out1;



  // <S19>/Logical Operator2
  assign Logical_Operator2_out1 =  ~ Logical_Operator1_out1;



  assign CRC_Chk = Logical_Operator2_out1;

endmodule  // Detector_ip_src_Check_CRC

