// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\ModeS_ADI_Codegen\Detector_ip_src_CalcSyncCorr.v
// Created: 2017-07-24 12:12:58
// 
// Generated by MATLAB 9.2 and HDL Coder 3.10
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Detector_ip_src_CalcSyncCorr
// Source Path: ModeS_ADI_Codegen/Detector/CalcSyncCorr
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Detector_ip_src_CalcSyncCorr
          (clk,
           reset,
           enb,
           In1,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In1;  // sfix16_En15
  output  signed [15:0] Out1;  // sfix16_En11

  wire signed [15:0] SyncCorr_out1;  // sfix16_En11


  // <S9>/SyncCorr
  Detector_ip_src_SyncCorr u_SyncCorr (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .SyncCorr_in(In1),  // sfix16_En15
                                       .SyncCorr_out(SyncCorr_out1)  // sfix16_En11
                                       );

  assign Out1 = SyncCorr_out1;

endmodule  // Detector_ip_src_CalcSyncCorr

