// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\ModeS_ADI_Codegen\Detector_ip_src_FrameDetect.v
// Created: 2017-07-24 12:12:58
// 
// Generated by MATLAB 9.2 and HDL Coder 3.10
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Detector_ip_src_FrameDetect
// Source Path: ModeS_ADI_Codegen/Detector/FrameDetect
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Detector_ip_src_FrameDetect
          (clk,
           reset,
           enb,
           bit_process,
           crc_valid,
           frame_valid);


  input   clk;
  input   reset;
  input   enb;
  input   bit_process;
  input   crc_valid;
  output  [15:0] frame_valid;  // uint16

  wire Logical_Operator1_out1;
  reg  Delay14_out1;
  wire Logical_Operator_out1;
  wire Logical_Operator2_out1;
  wire [15:0] Data_Type_Conversion_out1;  // uint16


  // <S10>/Logical Operator1
  assign Logical_Operator1_out1 =  ~ bit_process;



  // <S10>/Delay14
  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay14_out1 <= bit_process;
        end
      end
    end



  // <S10>/Logical Operator
  assign Logical_Operator_out1 = Logical_Operator1_out1 & Delay14_out1;



  // <S10>/Logical Operator2
  assign Logical_Operator2_out1 = crc_valid & Logical_Operator_out1;



  // <S10>/Data Type Conversion
  assign Data_Type_Conversion_out1 = {15'b0, Logical_Operator2_out1};



  assign frame_valid = Data_Type_Conversion_out1;

endmodule  // Detector_ip_src_FrameDetect

