# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/acozma/Documents/GitHub/MathWorks_tools/targeting_models/ADSB/hdl_prj/vivado_ip_prj/projects/pzsdr2/common/ccbrk_constr.xdc

# XDC: C:/Users/acozma/Documents/GitHub/MathWorks_tools/targeting_models/ADSB/hdl_prj/vivado_ip_prj/projects/pzsdr2/common/pzsdr2_constr.xdc

# XDC: C:/Users/acozma/Documents/GitHub/MathWorks_tools/targeting_models/ADSB/hdl_prj/vivado_ip_prj/projects/pzsdr2/common/pzsdr2_constr_lvds.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0}]

# IP: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0}]

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0}]

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0}]

# IP: bd/system/ip/system_sys_logic_inv_0/system_sys_logic_inv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_logic_inv_0 || ORIG_REF_NAME==system_sys_logic_inv_0}]

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0}]

# IP: bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0}]

# IP: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0}]

# IP: bd/system/ip/system_util_ad9361_dac_upack_0/system_util_ad9361_dac_upack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9361_dac_upack_0 || ORIG_REF_NAME==system_util_ad9361_dac_upack_0}]

# IP: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0}]

# IP: bd/system/ip/system_util_ad9361_adc_pack_0/system_util_ad9361_adc_pack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_pack_0 || ORIG_REF_NAME==system_util_ad9361_adc_pack_0}]

# IP: bd/system/ip/system_util_ad9361_adc_fifo_0/system_util_ad9361_adc_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_fifo_0 || ORIG_REF_NAME==system_util_ad9361_adc_fifo_0}]

# IP: bd/system/ip/system_util_ad9361_tdd_sync_0/system_util_ad9361_tdd_sync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ad9361_tdd_sync_0 || ORIG_REF_NAME==system_util_ad9361_tdd_sync_0}]

# IP: bd/system/ip/system_clkdiv_0/system_clkdiv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clkdiv_0 || ORIG_REF_NAME==system_clkdiv_0}]

# IP: bd/system/ip/system_clkdiv_reset_0/system_clkdiv_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clkdiv_reset_0 || ORIG_REF_NAME==system_clkdiv_reset_0}]

# IP: bd/system/ip/system_dac_fifo_0/system_dac_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dac_fifo_0 || ORIG_REF_NAME==system_dac_fifo_0}]

# IP: bd/system/ip/system_clkdiv_sel_logic_0/system_clkdiv_sel_logic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clkdiv_sel_logic_0 || ORIG_REF_NAME==system_clkdiv_sel_logic_0}]

# IP: bd/system/ip/system_concat_logic_0/system_concat_logic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_concat_logic_0 || ORIG_REF_NAME==system_concat_logic_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_axi_hp1_interconnect_0/system_axi_hp1_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp1_interconnect_0 || ORIG_REF_NAME==system_axi_hp1_interconnect_0}]

# IP: bd/system/ip/system_axi_hp2_interconnect_0/system_axi_hp2_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp2_interconnect_0 || ORIG_REF_NAME==system_axi_hp2_interconnect_0}]

# IP: bd/system/ip/system_sys_ps7_ENET1_GMII_RX_CLK_GND_0/system_sys_ps7_ENET1_GMII_RX_CLK_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps7_ENET1_GMII_RX_CLK_GND_0 || ORIG_REF_NAME==system_sys_ps7_ENET1_GMII_RX_CLK_GND_0}]

# IP: bd/system/ip/system_sys_ps7_ENET1_GMII_TX_CLK_GND_0/system_sys_ps7_ENET1_GMII_TX_CLK_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps7_ENET1_GMII_TX_CLK_GND_0 || ORIG_REF_NAME==system_sys_ps7_ENET1_GMII_TX_CLK_GND_0}]

# IP: bd/system/ip/system_axi_pz_xcvrlb_0/system_axi_pz_xcvrlb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_pz_xcvrlb_0 || ORIG_REF_NAME==system_axi_pz_xcvrlb_0}]

# IP: bd/system/ip/system_axi_gpreg_0/system_axi_gpreg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpreg_0 || ORIG_REF_NAME==system_axi_gpreg_0}]

# IP: bd/system/ip/system_Detector_ip_0_0/system_Detector_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_Detector_ip_0_0 || ORIG_REF_NAME==system_Detector_ip_0_0}]

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# XDC: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ad9361_0/axi_ad9361_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_axi_ad9361_0/ad_axi_ip_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0}] {/inst }]/inst ]]

# TCL: bd/system/ipshared/analog.com/axi_dmac_v1_0/bd.tcl

# XDC: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_util_ad9361_dac_upack_0/util_upack_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_dac_upack_0 || ORIG_REF_NAME==system_util_ad9361_dac_upack_0}] {/inst }]/inst ]]

# TCL: bd/system/ipshared/analog.com/axi_dmac_v1_0/bd.tcl

# XDC: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_util_ad9361_adc_pack_0/util_cpack_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_pack_0 || ORIG_REF_NAME==system_util_ad9361_adc_pack_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_util_ad9361_adc_fifo_0/util_wfifo_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_fifo_0 || ORIG_REF_NAME==system_util_ad9361_adc_fifo_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_util_ad9361_tdd_sync_0/util_tdd_sync_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_tdd_sync_0 || ORIG_REF_NAME==system_util_ad9361_tdd_sync_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clkdiv_0/util_clkdiv_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clkdiv_0 || ORIG_REF_NAME==system_clkdiv_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clkdiv_reset_0/system_clkdiv_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clkdiv_reset_0 || ORIG_REF_NAME==system_clkdiv_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_clkdiv_reset_0/system_clkdiv_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clkdiv_reset_0 || ORIG_REF_NAME==system_clkdiv_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_clkdiv_reset_0/system_clkdiv_reset_0_ooc.xdc

# XDC: bd/system/ip/system_dac_fifo_0/util_rfifo_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_dac_fifo_0 || ORIG_REF_NAME==system_dac_fifo_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_axi_pz_xcvrlb_0/axi_xcvrlb_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_pz_xcvrlb_0 || ORIG_REF_NAME==system_axi_pz_xcvrlb_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc

# XDC: C:/Users/acozma/Documents/GitHub/MathWorks_tools/targeting_models/ADSB/hdl_prj/vivado_ip_prj/projects/common/xilinx/compression_system_constr.xdc

# XDC: C:/Users/acozma/Documents/GitHub/MathWorks_tools/targeting_models/ADSB/hdl_prj/vivado_ip_prj/projects/pzsdr2/common/pzsdr2_constr.xdc

# XDC: C:/Users/acozma/Documents/GitHub/MathWorks_tools/targeting_models/ADSB/hdl_prj/vivado_ip_prj/projects/pzsdr2/common/pzsdr2_constr_lvds.xdc

# XDC: C:/Users/acozma/Documents/GitHub/MathWorks_tools/targeting_models/ADSB/hdl_prj/vivado_ip_prj/projects/pzsdr2/common/ccbrk_constr.xdc
